-- V1__create_zones.sql
CREATE TABLE zones (
    id          INTEGER PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    borough     VARCHAR(50)  NOT NULL,
    service_zone VARCHAR(50)
);

INSERT INTO zones (id, name, borough, service_zone) VALUES
(1, 'Newark Airport', 'EWR', 'Airports'),
(2, 'Jamaica Bay', 'Queens', 'Boro Zone'),
(3, 'Allerton/Pelham Gardens', 'Bronx', 'Boro Zone'),
(4, 'Alphabet City', 'Manhattan', 'Yellow Zone'),
(5, 'Arden Heights', 'Staten Island', 'Boro Zone'),
(6, 'Arrochar/Fort Wadsworth', 'Staten Island', 'Boro Zone'),
(7, 'Astoria', 'Queens', 'Boro Zone'),
(8, 'Astoria Park', 'Queens', 'Boro Zone'),
(9, 'Auburndale', 'Queens', 'Boro Zone'),
(10, 'Baisley Park', 'Queens', 'Boro Zone'),
(11, 'Bath Beach', 'Brooklyn', 'Boro Zone'),
(12, 'Battery Park', 'Manhattan', 'Yellow Zone'),
(13, 'Battery Park City', 'Manhattan', 'Yellow Zone'),
(14, 'Bay Ridge', 'Brooklyn', 'Boro Zone'),
(15, 'Bay Terrace/Fort Totten', 'Queens', 'Boro Zone'),
(16, 'Bayside', 'Queens', 'Boro Zone'),
(17, 'Bedford', 'Brooklyn', 'Boro Zone'),
(18, 'Bedford Park', 'Bronx', 'Boro Zone'),
(19, 'Bellerose', 'Queens', 'Boro Zone'),
(20, 'Belmont', 'Bronx', 'Boro Zone'),
(21, 'Bensonhurst East', 'Brooklyn', 'Boro Zone'),
(22, 'Bensonhurst West', 'Brooklyn', 'Boro Zone'),
(23, 'Bloomberg/East Midtown', 'Manhattan', 'Yellow Zone'),
(24, 'Bloomfield/Emerson Hill', 'Staten Island', 'Boro Zone'),
(25, 'Boerum Hill', 'Brooklyn', 'Boro Zone'),
(26, 'Borough Park', 'Brooklyn', 'Boro Zone'),
(27, 'Breezy Point/Fort Tilden/Riis Beach', 'Queens', 'Boro Zone'),
(28, 'Briarwood/Jamaica Hills', 'Queens', 'Boro Zone'),
(29, 'Brighton Beach', 'Brooklyn', 'Boro Zone'),
(30, 'Broad Channel', 'Queens', 'Boro Zone'),
(31, 'Bronx Park', 'Bronx', 'Boro Zone'),
(32, 'Bronxdale', 'Bronx', 'Boro Zone'),
(33, 'Brooklyn Heights', 'Brooklyn', 'Boro Zone'),
(34, 'Brooklyn Navy Yard', 'Brooklyn', 'Boro Zone'),
(35, 'Brownsville', 'Brooklyn', 'Boro Zone'),
(36, 'Bushwick North', 'Brooklyn', 'Boro Zone'),
(37, 'Bushwick South', 'Brooklyn', 'Boro Zone'),
(38, 'Cambria Heights', 'Queens', 'Boro Zone'),
(39, 'Canarsie', 'Brooklyn', 'Boro Zone'),
(40, 'Carroll Gardens', 'Brooklyn', 'Boro Zone'),
(41, 'Central Harlem', 'Manhattan', 'Boro Zone'),
(42, 'Central Harlem North', 'Manhattan', 'Boro Zone'),
(43, 'Central Park', 'Manhattan', 'Yellow Zone'),
(44, 'Charleston/Tottenville', 'Staten Island', 'Boro Zone'),
(45, 'Chinatown', 'Manhattan', 'Yellow Zone'),
(46, 'City Island', 'Bronx', 'Boro Zone'),
(47, 'Claremont/Bathgate', 'Bronx', 'Boro Zone'),
(48, 'Clinton East', 'Manhattan', 'Yellow Zone'),
(49, 'Clinton Hill', 'Brooklyn', 'Boro Zone'),
(50, 'Clinton West', 'Manhattan', 'Yellow Zone'),
(51, 'Co-Op City', 'Bronx', 'Boro Zone'),
(52, 'Cobble Hill', 'Brooklyn', 'Boro Zone'),
(53, 'College Point', 'Queens', 'Boro Zone'),
(54, 'Columbia Circle', 'Manhattan', 'Yellow Zone'),
(55, 'Columbia Street', 'Brooklyn', 'Boro Zone'),
(56, 'Coney Island', 'Brooklyn', 'Boro Zone'),
(57, 'Corona', 'Queens', 'Boro Zone'),
(58, 'Country Club', 'Bronx', 'Boro Zone'),
(59, 'Crotona Park', 'Bronx', 'Boro Zone'),
(60, 'Crotona Park East', 'Bronx', 'Boro Zone'),
(61, 'Crown Heights North', 'Brooklyn', 'Boro Zone'),
(62, 'Crown Heights South', 'Brooklyn', 'Boro Zone'),
(63, 'Cypress Hills', 'Brooklyn', 'Boro Zone'),
(64, 'Douglaston', 'Queens', 'Boro Zone'),
(65, 'Downtown Brooklyn/MetroTech', 'Brooklyn', 'Boro Zone'),
(66, 'DUMBO/Vinegar Hill', 'Brooklyn', 'Boro Zone'),
(67, 'Dyker Heights', 'Brooklyn', 'Boro Zone'),
(68, 'East Chelsea', 'Manhattan', 'Yellow Zone'),
(69, 'East Concourse/Concourse Village', 'Bronx', 'Boro Zone'),
(70, 'East Elmhurst', 'Queens', 'Boro Zone'),
(71, 'East Flatbush/Farragut', 'Brooklyn', 'Boro Zone'),
(72, 'East Flatbush/Remsen Village', 'Brooklyn', 'Boro Zone'),
(73, 'East Flushing', 'Queens', 'Boro Zone'),
(74, 'East Harlem North', 'Manhattan', 'Boro Zone'),
(75, 'East Harlem South', 'Manhattan', 'Boro Zone'),
(76, 'East New York', 'Brooklyn', 'Boro Zone'),
(77, 'East New York/Pennsylvania Avenue', 'Brooklyn', 'Boro Zone'),
(78, 'East Tremont', 'Bronx', 'Boro Zone'),
(79, 'East Village', 'Manhattan', 'Yellow Zone'),
(80, 'East Williamsburg', 'Brooklyn', 'Boro Zone'),
(81, 'Eastchester', 'Bronx', 'Boro Zone'),
(82, 'Elmhurst', 'Queens', 'Boro Zone'),
(83, 'Elmhurst/Maspeth', 'Queens', 'Boro Zone'),
(84, 'Eltingville/Annadale/Prince''s Bay', 'Staten Island', 'Boro Zone'),
(85, 'Erasmus', 'Brooklyn', 'Boro Zone'),
(86, 'Far Rockaway', 'Queens', 'Boro Zone'),
(87, 'Financial District North', 'Manhattan', 'Yellow Zone'),
(88, 'Financial District South', 'Manhattan', 'Yellow Zone'),
(89, 'Flatbush/Ditmas Park', 'Brooklyn', 'Boro Zone'),
(90, 'Flatiron', 'Manhattan', 'Yellow Zone'),
(91, 'Flatlands', 'Brooklyn', 'Boro Zone'),
(92, 'Flushing', 'Queens', 'Boro Zone'),
(93, 'Flushing Meadows-Corona Park', 'Queens', 'Boro Zone'),
(94, 'Fordham South', 'Bronx', 'Boro Zone'),
(95, 'Forest Hills', 'Queens', 'Boro Zone'),
(96, 'Forest Park/Highland Park', 'Queens', 'Boro Zone'),
(97, 'Fort Greene', 'Brooklyn', 'Boro Zone'),
(98, 'Fresh Meadows', 'Queens', 'Boro Zone'),
(99, 'Freshkills Park', 'Staten Island', 'Boro Zone'),
(100, 'Garment District', 'Manhattan', 'Yellow Zone'),
(101, 'Glen Oaks', 'Queens', 'Boro Zone'),
(102, 'Glendale', 'Queens', 'Boro Zone'),
(103, 'Governor''s Island/Ellis Island/Liberty Island', 'Manhattan', 'Yellow Zone'),
(104, 'Gowanus', 'Brooklyn', 'Boro Zone'),
(105, 'Gramercy', 'Manhattan', 'Yellow Zone'),
(106, 'Gravesend', 'Brooklyn', 'Boro Zone'),
(107, 'Great Kills', 'Staten Island', 'Boro Zone'),
(108, 'Great Kills Park', 'Staten Island', 'Boro Zone'),
(109, 'Green-Wood Cemetery', 'Brooklyn', 'Boro Zone'),
(110, 'Greenpoint', 'Brooklyn', 'Boro Zone'),
(111, 'Greenwich Village North', 'Manhattan', 'Yellow Zone'),
(112, 'Greenwich Village South', 'Manhattan', 'Yellow Zone'),
(113, 'Grymes Hill/Clifton', 'Staten Island', 'Boro Zone'),
(114, 'Hamilton Heights', 'Manhattan', 'Boro Zone'),
(115, 'Hammels/Arverne', 'Queens', 'Boro Zone'),
(116, 'Heartland Village/Todt Hill', 'Staten Island', 'Boro Zone'),
(117, 'Highbridge', 'Bronx', 'Boro Zone'),
(118, 'Highbridge Park', 'Manhattan', 'Boro Zone'),
(119, 'Hillcrest/Pomonok', 'Queens', 'Boro Zone'),
(120, 'Hollis', 'Queens', 'Boro Zone'),
(121, 'Homecrest', 'Brooklyn', 'Boro Zone'),
(122, 'Howard Beach', 'Queens', 'Boro Zone'),
(123, 'Hudson Sq', 'Manhattan', 'Yellow Zone'),
(124, 'Hunts Point', 'Bronx', 'Boro Zone'),
(125, 'Inwood', 'Manhattan', 'Boro Zone'),
(126, 'Inwood Hill Park', 'Manhattan', 'Boro Zone'),
(127, 'Jackson Heights', 'Queens', 'Boro Zone'),
(128, 'Jamaica', 'Queens', 'Boro Zone'),
(129, 'Jamaica Estates', 'Queens', 'Boro Zone'),
(130, 'JFK Airport', 'Queens', 'Airports'),
(131, 'Kensington', 'Brooklyn', 'Boro Zone'),
(132, 'Kew Gardens', 'Queens', 'Boro Zone'),
(133, 'Kew Gardens Hills', 'Queens', 'Boro Zone'),
(134, 'Kingsbridge Heights', 'Bronx', 'Boro Zone'),
(135, 'Kingsbridge/Marble Hill', 'Manhattan', 'Boro Zone'),
(136, 'La Guardia Airport', 'Queens', 'Airports'),
(137, 'Laurelton', 'Queens', 'Boro Zone'),
(138, 'Lenox Hill East', 'Manhattan', 'Yellow Zone'),
(139, 'Lenox Hill West', 'Manhattan', 'Yellow Zone'),
(140, 'Lincoln Square East', 'Manhattan', 'Yellow Zone'),
(141, 'Lincoln Square West', 'Manhattan', 'Yellow Zone'),
(142, 'Little Italy/NoLiTa', 'Manhattan', 'Yellow Zone'),
(143, 'Long Island City/Hunters Point', 'Queens', 'Boro Zone'),
(144, 'Long Island City/Queens Plaza', 'Queens', 'Boro Zone'),
(145, 'Longwood', 'Bronx', 'Boro Zone'),
(146, 'Lower East Side', 'Manhattan', 'Yellow Zone'),
(147, 'Madison', 'Manhattan', 'Yellow Zone'),
(148, 'Manhattan Beach', 'Brooklyn', 'Boro Zone'),
(149, 'Manhattan Valley', 'Manhattan', 'Yellow Zone'),
(150, 'Manhattanville', 'Manhattan', 'Boro Zone'),
(151, 'Marble Hill', 'Manhattan', 'Boro Zone'),
(152, 'Marine Park/Floyd Bennett Field', 'Brooklyn', 'Boro Zone'),
(153, 'Marine Park/Mill Basin', 'Brooklyn', 'Boro Zone'),
(154, 'Mariners Harbor', 'Staten Island', 'Boro Zone'),
(155, 'Maspeth', 'Queens', 'Boro Zone'),
(156, 'Meatpacking/West Village West', 'Manhattan', 'Yellow Zone'),
(157, 'Melrose South', 'Bronx', 'Boro Zone'),
(158, 'Middle Village', 'Queens', 'Boro Zone'),
(159, 'Midtown Center', 'Manhattan', 'Yellow Zone'),
(160, 'Midtown East', 'Manhattan', 'Yellow Zone'),
(161, 'Midtown North', 'Manhattan', 'Yellow Zone'),
(162, 'Midtown South', 'Manhattan', 'Yellow Zone'),
(163, 'Midwood', 'Brooklyn', 'Boro Zone'),
(164, 'Morningside Heights', 'Manhattan', 'Boro Zone'),
(165, 'Morrisania/Melrose', 'Bronx', 'Boro Zone'),
(166, 'Mott Haven/Port Morris', 'Bronx', 'Boro Zone'),
(167, 'Mount Hope', 'Bronx', 'Boro Zone'),
(168, 'Murray Hill', 'Manhattan', 'Yellow Zone'),
(169, 'Murray Hill-Queens', 'Queens', 'Boro Zone'),
(170, 'New Dorp/Midland Beach', 'Staten Island', 'Boro Zone'),
(171, 'North Corona', 'Queens', 'Boro Zone'),
(172, 'Norwood', 'Bronx', 'Boro Zone'),
(173, 'Oakland Gardens', 'Queens', 'Boro Zone'),
(174, 'Oakwood', 'Staten Island', 'Boro Zone'),
(175, 'Ocean Hill', 'Brooklyn', 'Boro Zone'),
(176, 'Ocean Parkway South', 'Brooklyn', 'Boro Zone'),
(177, 'Old Astoria', 'Queens', 'Boro Zone'),
(178, 'Ozone Park', 'Queens', 'Boro Zone'),
(179, 'Park Slope', 'Brooklyn', 'Boro Zone'),
(180, 'Parkchester', 'Bronx', 'Boro Zone'),
(181, 'Pelham Bay', 'Bronx', 'Boro Zone'),
(182, 'Pelham Bay Park', 'Bronx', 'Boro Zone'),
(183, 'Pelham Parkway', 'Bronx', 'Boro Zone'),
(184, 'Penn Station/Madison Sq West', 'Manhattan', 'Yellow Zone'),
(185, 'Port Richmond', 'Staten Island', 'Boro Zone'),
(186, 'Prospect-Lefferts Gardens', 'Brooklyn', 'Boro Zone'),
(187, 'Prospect Heights', 'Brooklyn', 'Boro Zone'),
(188, 'Prospect Park', 'Brooklyn', 'Boro Zone'),
(189, 'Queens Village', 'Queens', 'Boro Zone'),
(190, 'Queensboro Hill', 'Queens', 'Boro Zone'),
(191, 'Queensbridge/Ravenswood', 'Queens', 'Boro Zone'),
(192, 'Randalls Island', 'Manhattan', 'Yellow Zone'),
(193, 'Red Hook', 'Brooklyn', 'Boro Zone'),
(194, 'Rego Park', 'Queens', 'Boro Zone'),
(195, 'Richmond Hill', 'Queens', 'Boro Zone'),
(196, 'Ridgewood', 'Queens', 'Boro Zone'),
(197, 'Rikers Island', 'Queens', 'Boro Zone'),
(198, 'Riverdale/North Riverdale/Fieldston', 'Bronx', 'Boro Zone'),
(199, 'Rockaway Park', 'Queens', 'Boro Zone'),
(200, 'Roosevelt Island', 'Manhattan', 'Boro Zone'),
(201, 'Rosedale', 'Queens', 'Boro Zone'),
(202, 'Rossville/Woodrow', 'Staten Island', 'Boro Zone'),
(203, 'Rugby', 'Brooklyn', 'Boro Zone'),
(204, 'Sheepshead Bay', 'Brooklyn', 'Boro Zone'),
(205, 'SoHo', 'Manhattan', 'Yellow Zone'),
(206, 'Soundview/Bruckner', 'Bronx', 'Boro Zone'),
(207, 'Soundview/Castle Hill', 'Bronx', 'Boro Zone'),
(208, 'South Beach/Dongan Hills', 'Staten Island', 'Boro Zone'),
(209, 'South Jamaica', 'Queens', 'Boro Zone'),
(210, 'South Ozone Park', 'Queens', 'Boro Zone'),
(211, 'South Williamsburg', 'Brooklyn', 'Boro Zone'),
(212, 'Springfield Gardens North', 'Queens', 'Boro Zone'),
(213, 'Springfield Gardens South', 'Queens', 'Boro Zone'),
(214, 'Spuyten Duyvil/Kingsbridge', 'Bronx', 'Boro Zone'),
(215, 'St. Albans', 'Queens', 'Boro Zone'),
(216, 'St. George/New Brighton', 'Staten Island', 'Boro Zone'),
(217, 'St. Michaels Cemetery/Woodside', 'Queens', 'Boro Zone'),
(218, 'Stapleton', 'Staten Island', 'Boro Zone'),
(219, 'Starrett City', 'Brooklyn', 'Boro Zone'),
(220, 'Steinway', 'Queens', 'Boro Zone'),
(221, 'Stuy Town/Peter Cooper Village', 'Manhattan', 'Yellow Zone'),
(222, 'Stuyvesant Heights', 'Brooklyn', 'Boro Zone'),
(223, 'Sunnyside', 'Queens', 'Boro Zone'),
(224, 'Sunset Park East', 'Brooklyn', 'Boro Zone'),
(225, 'Sunset Park West', 'Brooklyn', 'Boro Zone'),
(226, 'Throgs Neck', 'Bronx', 'Boro Zone'),
(227, 'Times Sq/Theatre District', 'Manhattan', 'Yellow Zone'),
(228, 'TriBeCa/Civic Center', 'Manhattan', 'Yellow Zone'),
(229, 'Two Bridges/Seward Park', 'Manhattan', 'Yellow Zone'),
(230, 'Union Sq', 'Manhattan', 'Yellow Zone'),
(231, 'University Heights/Morris Heights', 'Bronx', 'Boro Zone'),
(232, 'Upper East Side North', 'Manhattan', 'Yellow Zone'),
(233, 'Upper East Side South', 'Manhattan', 'Yellow Zone'),
(234, 'Upper West Side North', 'Manhattan', 'Yellow Zone'),
(235, 'Upper West Side South', 'Manhattan', 'Yellow Zone'),
(236, 'Van Cortlandt Park', 'Bronx', 'Boro Zone'),
(237, 'Van Cortlandt Village', 'Bronx', 'Boro Zone'),
(238, 'Van Nest/Morris Park', 'Bronx', 'Boro Zone'),
(239, 'Washington Heights North', 'Manhattan', 'Boro Zone'),
(240, 'Washington Heights South', 'Manhattan', 'Boro Zone'),
(241, 'West Brighton', 'Staten Island', 'Boro Zone'),
(242, 'West Concourse', 'Bronx', 'Boro Zone'),
(243, 'West Farms/Bronx River', 'Bronx', 'Boro Zone'),
(244, 'West Village', 'Manhattan', 'Yellow Zone'),
(245, 'Westchester Village/Unionport', 'Bronx', 'Boro Zone'),
(246, 'Westerleigh', 'Staten Island', 'Boro Zone'),
(247, 'Whitestone', 'Queens', 'Boro Zone'),
(248, 'Willets Point', 'Queens', 'Boro Zone'),
(249, 'Williamsbridge/Olinville', 'Bronx', 'Boro Zone'),
(250, 'Williamsburg (North Side)', 'Brooklyn', 'Boro Zone'),
(251, 'Williamsburg (South Side)', 'Brooklyn', 'Boro Zone'),
(252, 'Windsor Terrace', 'Brooklyn', 'Boro Zone'),
(253, 'Woodhaven', 'Queens', 'Boro Zone'),
(254, 'Woodlawn/Wakefield', 'Bronx', 'Boro Zone'),
(255, 'Woodside', 'Queens', 'Boro Zone'),
(256, 'World Trade Center', 'Manhattan', 'Yellow Zone'),
(257, 'Yorkville East', 'Manhattan', 'Yellow Zone'),
(258, 'Yorkville West', 'Manhattan', 'Yellow Zone'),
(259, 'Cambria Heights', 'Queens', 'Boro Zone'),
(260, 'Broad Channel', 'Queens', 'Boro Zone'),
(261, 'Unknown', 'Unknown', 'N/A'),
(262, 'Outside NYC', 'Unknown', 'N/A'),
(263, 'NV', 'Unknown', 'N/A'),
(264, 'NA', 'Unknown', 'N/A'),
(265, 'N/A', 'Unknown', 'N/A');