apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: data-platform
type: Opaque
stringData:
  pg-user: {{ .Values.secrets.pg.user | quote }}
  pg-password: {{ .Values.secrets.pg.password | quote }}
  pg-dbname: {{ .Values.secrets.pg.dbname | quote }}
  minio-access-key: {{ .Values.secrets.minio.accessKey | quote }}
  minio-secret-key: {{ .Values.secrets.minio.secretKey | quote }}
  airflow-postgres-user: {{ .Values.secrets.airflow.postgresUser | quote }}
  airflow-postgres-password: {{ .Values.secrets.airflow.postgresPassword | quote }}
  airflow-postgres-db: {{ .Values.secrets.airflow.postgresDb | quote }}
  airflow-fernet-key: {{ .Values.secrets.airflow.fernetKey | quote }}
  airflow-www-user: {{ .Values.secrets.airflow.wwwUser | quote }}
  airflow-www-password: {{ .Values.secrets.airflow.wwwPassword | quote }}
  iceberg-postgres-user: {{ .Values.secrets.icebergPostgres.user | quote }}
  iceberg-postgres-password: {{ .Values.secrets.icebergPostgres.password | quote }}
  iceberg-postgres-db: {{ .Values.secrets.icebergPostgres.db | quote }}
